image: node:latest

stages:
  - test
  - release


test:
  stage: test
  before_script:
    - yarn
  script:
    - yarn test

publish:
  stage: release
  # Don't need yarn install here, as prerelease takes care of that.
  script:
    - yarn build
    - yarn release
