image: node:latest

stages:
  - test
  - release

before_script:
  - npm install -g pnpm
  - pnpm install

test:
  stage: test
  script:
    - pnpm run test

publish:
  stage: release
  script:
    - pnpm run release
